// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: follow_feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const followFeed = `-- name: FollowFeed :one
INSERT INTO follow_feed (feed_id, user_id, created_at, updated_at)
VALUES ($1, $2, $3, $4)
RETURNING id, feed_id, user_id, created_at, updated_at
`

type FollowFeedParams struct {
	FeedID    int32
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) FollowFeed(ctx context.Context, arg FollowFeedParams) (FollowFeed, error) {
	row := q.db.QueryRowContext(ctx, followFeed,
		arg.FeedID,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i FollowFeed
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
